AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Salesforce-Stripe Payment Processing Middleware

  FastAPI-based webhook handler with SQS processing for Stripe → Salesforce integration

# Global configuration for all Lambda functions
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        # Application settings
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !Ref LogLevel
        APP_NAME: Salesforce-Stripe Middleware

        # AWS Resources (auto-populated by CloudFormation)
        SQS_QUEUE_URL: !Ref StripeEventQueue
        # Note: AWS_REGION is automatically provided by Lambda runtime

        # DynamoDB table for caching (replaces Redis)
        DYNAMODB_TABLE_NAME: !Ref CacheTable

        # Secrets Manager references (values stored securely)
        STRIPE_WEBHOOK_SECRET_ARN: !Ref StripeWebhookSecret
        SALESFORCE_CLIENT_SECRET_ARN: !Ref SalesforceClientSecret

# Parameters for customization during deployment
Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
    Description: Logging level

  StripeApiKey:
    Type: String
    NoEcho: true
    Description: Stripe API Key (will be stored in Secrets Manager)

  StripeWebhookSecretValue:
    Type: String
    NoEcho: true
    Description: Stripe Webhook Signing Secret

  SalesforceClientId:
    Type: String
    Description: Salesforce Connected App Client ID

  SalesforceClientSecretValue:
    Type: String
    NoEcho: true
    Description: Salesforce Connected App Client Secret

  SalesforceInstanceUrl:
    Type: String
    Default: https://login.salesforce.com
    Description: Salesforce instance URL

# AWS Resources to create
Resources:

  # ==========================================
  # SECRETS MANAGER - Secure credential storage
  # ==========================================

  StripeApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-stripe-api-key
      Description: Stripe API Key for webhook processing
      SecretString: !Ref StripeApiKey

  StripeWebhookSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-stripe-webhook-secret
      Description: Stripe Webhook Signing Secret
      SecretString: !Ref StripeWebhookSecretValue

  SalesforceClientSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-salesforce-client-secret
      Description: Salesforce Connected App Client Secret
      SecretString: !Sub |
        {
          "client_id": "${SalesforceClientId}",
          "client_secret": "${SalesforceClientSecretValue}",
          "instance_url": "${SalesforceInstanceUrl}"
        }

  # ==========================================
  # SQS QUEUES - Event buffering
  # ==========================================

  # Dead Letter Queue for failed messages
  StripeEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-stripe-events-dlq
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeout: 300
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Main event queue with DLQ configuration
  StripeEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-stripe-events
      VisibilityTimeout: 180  # 3 minutes (2x Lambda timeout)
      MessageRetentionPeriod: 345600  # 4 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt StripeEventDLQ.Arn
        maxReceiveCount: 5  # Retry 5 times before sending to DLQ
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # DYNAMODB TABLE - Token Caching & Storage
  # ==========================================

  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-cache
      BillingMode: PAY_PER_REQUEST  # Auto-scaling, no provisioned capacity
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH  # Partition key
        - AttributeName: sk
          KeyType: RANGE  # Sort key (optional, for sorted sets)
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true  # Auto-delete expired items
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES  # Optional: for audit/replication
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Token caching and temporary storage

  # ==========================================
  # LAMBDA FUNCTION - Webhook Receiver
  # ==========================================

  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-webhook-receiver
      CodeUri: .
      Handler: lambda_handler.lambda_handler
      Description: Receives and verifies Stripe webhooks, pushes to SQS
      Timeout: 10  # Quick response to Stripe (< 5 seconds target)
      MemorySize: 256
      Environment:
        Variables:
          STRIPE_API_KEY_ARN: !Ref StripeApiKeySecret

          # --- These are the ARNs for secrets, correctly passed as ENV VARS ---
          STRIPE_API_KEY_ARN: !Ref StripeApiKeySecret
          STRIPE_WEBHOOK_SECRET_ARN: !Ref StripeWebhookSecret
          SALESFORCE_CLIENT_SECRET_ARN: !Ref SalesforceClientSecret

          # Other direct environment variables the Lambda needs
          SALESFORCE_INSTANCE_URL: !Ref SalesforceInstanceUrl
      Policies:
        # Permission to send messages to SQS
        - SQSSendMessagePolicy:
            QueueName: !GetAtt StripeEventQueue.QueueName
        # Permission to read/write DynamoDB
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
        # Permission to read secrets
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref StripeApiKeySecret
              - !Ref StripeWebhookSecret
              - !Ref SalesforceClientSecret
      Events:
        # Catch-all route - let FastAPI handle all routing
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref WebhookHttpApi
        # Root path
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref WebhookHttpApi
      Tags:
        Environment: !Ref Environment

  # CloudWatch Log Group for Webhook Function
  WebhookFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WebhookFunction}
      RetentionInDays: 7

  # ==========================================
  # LAMBDA FUNCTION - SQS Event Processor
  # ==========================================

  SqsWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-sqs-worker
      CodeUri: .
      Handler: sqs_worker.lambda_handler
      Description: Processes Stripe events from SQS and updates Salesforce
      Timeout: 90  # Longer timeout for Salesforce API calls
      MemorySize: 512
      # ReservedConcurrentExecutions: 10  # Uncomment if you need to limit concurrency
      Policies:
        # Permission to receive messages from SQS
        - SQSPollerPolicy:
            QueueName: !GetAtt StripeEventQueue.QueueName
        # Permission to read/write DynamoDB
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
        # Permission to read secrets
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref StripeApiKeySecret
              - !Ref StripeWebhookSecret
              - !Ref SalesforceClientSecret
      Events:
        # Triggered by SQS messages
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt StripeEventQueue.Arn
            BatchSize: 5  # Process 5 messages at a time
            MaximumBatchingWindowInSeconds: 10  # Wait up to 10s to batch messages
            FunctionResponseTypes:
              - ReportBatchItemFailures  # Enable partial batch failures
      Tags:
        Environment: !Ref Environment

  # CloudWatch Log Group for SQS Worker Function
  SqsWorkerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SqsWorkerFunction}
      RetentionInDays: 7

  # ==========================================
  # API GATEWAY - HTTP API for webhooks
  # ==========================================

  WebhookHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Description: !Sub API Gateway for Stripe webhooks - ${Environment}
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
        AllowHeaders:
          - Content-Type
          - Stripe-Signature
      Tags:
        Environment: !Ref Environment

  # ==========================================
  # CLOUDWATCH ALARMS - Monitoring
  # ==========================================

  # Alarm for webhook function errors
  WebhookErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-webhook-errors
      AlarmDescription: Alert when webhook function has high error rate
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref WebhookFunction
      TreatMissingData: notBreaching

  # Alarm for DLQ messages (failed events)
  DlqMessagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-dlq-messages
      AlarmDescription: Alert when messages appear in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt StripeEventDLQ.QueueName
      TreatMissingData: notBreaching

  # Alarm for high queue depth
  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-queue-depth
      AlarmDescription: Alert when queue has too many pending messages
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt StripeEventQueue.QueueName
      TreatMissingData: notBreaching

# Outputs - Important values to reference after deployment
Outputs:
  WebhookUrl:
    Description: Stripe Webhook URL (configure this in Stripe Dashboard)
    Value: !Sub https://${WebhookHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook/stripe
    Export:
      Name: !Sub ${AWS::StackName}-WebhookUrl

  WebhookFunctionArn:
    Description: Webhook Lambda Function ARN
    Value: !GetAtt WebhookFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WebhookFunctionArn

  SqsWorkerFunctionArn:
    Description: SQS Worker Lambda Function ARN
    Value: !GetAtt SqsWorkerFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SqsWorkerFunctionArn

  QueueUrl:
    Description: SQS Queue URL
    Value: !Ref StripeEventQueue
    Export:
      Name: !Sub ${AWS::StackName}-QueueUrl

  DlqUrl:
    Description: Dead Letter Queue URL
    Value: !Ref StripeEventDLQ
    Export:
      Name: !Sub ${AWS::StackName}-DlqUrl

  ApiId:
    Description: API Gateway ID
    Value: !Ref WebhookHttpApi
    Export:
      Name: !Sub ${AWS::StackName}-ApiId
